# =============================================================================
# project.yaml — プロジェクトコンテキストファイル（全プロセスの SSOT）
# =============================================================================

meta:
  version: "1.0"
  ticket_id: "ELSA-001"
  task_name: "Elsa Workflow システム機能拡張（Activity DLL読み込み・JSON管理・MassTransit連携・E2Eテスト整備）"
  target_repo: "elsa"
  branch: "feature/ELSA-001"
  created_at: "2026-02-20T05:20:00+00:00"
  updated_at: "2026-02-20T05:42:59+00:00"
setup:
  description:
    overview: |
      NagasakaH/elsa リポジトリのプロトタイプ実装（tmpブランチ）を参考に、
      masterブランチから新規featureブランチを作成し、以下の機能を正式に実装・テスト基盤を整備する：
      - Activity DLL の動的読み込み機構
      - サンプル Activity DLL プロジェクト
      - Elsa Studio の JSON 読み込みを使ったワークフロー管理（Elsa Studio GUI で編集可能）
      - MassTransit を使った任意のワークフローの実行・停止
      - 包括的なテスト基盤（単体・結合・E2E）
    purpose: |
      現在 tmp ブランチにプロトタイプ状態で存在する実装を、正式なブランチで整理・統合し、
      プロダクション品質のコードとテスト基盤を構築する。
    background: |
      - tmp ブランチに Activities.Loader、MassTransit 連携、JSON カタログ管理等のお試し実装が存在する
      - master ブランチは基本的な構成のみ（カスタム Activity 直書き、SQLite、テストなし）
      - compose.yml に PostgreSQL + RabbitMQ の Docker 構成が定義済み
      - Elsa 3.4.x ベース、.NET 8 ターゲット
    requirements:
      functional:
        - "Activity DLL 動的読み込み機構（外部フォルダからDLLをスキャンしアクティビティを自動登録）"
        - "サンプル Activity DLL プロジェクト（テンプレートとして利用可能）"
        - "ワークフロー JSON の起動時読み込み・カタログ管理（WorkflowCatalog）"
        - "Elsa Studio GUI でのワークフロー JSON 編集・保存対応"
        - "要求（テンプレート等）からワークフロー JSON を生成する仕組み"
        - "MassTransit を使ったワークフローの実行（StartWorkflowCommand）"
        - "MassTransit を使ったワークフローの停止"
        - "ワークフローステータスのイベント発行（WorkflowStatusEvent）"
      non_functional:
        - "テストカバレッジの充実（単体・結合・E2E の3層）"
        - "外部DLLのロード安全性（不正DLLのエラーハンドリング）"
        - "ワークフロー JSON のバリデーション（スキーマ準拠チェック）"
        - "Docker Compose ベースの開発環境で完結する構成"
    acceptance_criteria:
      - "Activity DLL を外部フォルダから動的にロードでき、単体テストで検証済み"
      - "ロードしたアクティビティが Elsa Studio のアクティビティ一覧に表示される（結合テスト検証済み）"
      - "ワークフロー JSON をカタログから読み込み、Elsa に登録できる"
      - "Elsa Studio GUI でワークフロー JSON の編集・保存ができる"
      - "要求からワークフロー JSON を生成する仕組みが動作する"
      - "MassTransit 経由でワークフローの実行・停止ができる"
      - "MassTransit Consumer の単体・結合テストが通過する"
      - "ワークフロー JSON バリデーション（不正JSONのエラーハンドリング含む）テスト通過"
      - "ワークフローライフサイクル（作成→公開→実行→完了→停止）のAPI E2Eテスト通過"
      - "Playwright CLI でのE2Eテスト（Studio上でのワークフロー編集・操作確認）通過"
    scope:
      - "Activity DLL 動的読み込み機構の実装とテスト"
      - "サンプル Activity DLL テンプレートの作成"
      - "ワークフロー JSON カタログ管理の実装とテスト"
      - "Elsa Studio 連携（GUI編集対応）"
      - "ワークフロー JSON 生成機構"
      - "MassTransit 連携（ワークフロー実行・停止）の実装とテスト"
      - "Playwright CLI による E2E テスト整備"
      - "PostgreSQL + RabbitMQ を使った結合テスト環境"
    out_of_scope:
      - "本番環境へのデプロイ"
      - "ユーザー認証・権限管理の本格実装"
      - "RPC Service の新規追加"
    notes: |
      tmp ブランチの実装を参考にしつつ、新規ブランチで整理して実装する。
      Elsa 3.4.x / .NET 8 ベース。テスト環境は Docker Compose。
  related_repositories: []
  target_repositories:
    - name: "elsa"
      url: "git@github.com:NagasakaH/elsa.git"
      base_branch: "master"
  options:
    create_design_document: true
    design_document_dir: "docs"
    submodules_dir: "submodules"
brainstorming:
  status: "completed"
  started_at: "2026-02-20T05:15:00+00:00"
  completed_at: "2026-02-20T05:25:00+00:00"
  summary: |
    tmpブランチの設計を踏襲しつつ整理・改善する方針で合意。
    DB は PostgreSQL へ移行、MassTransit は Elsa 標準拡張を使用（独自改造なし）。
    E2E テストは C# Playwright (xUnit) で dotnet test 統一。
  decisions:
    - question: "tmpブランチの設計をそのまま使うか再設計か"
      decision: "tmpブランチの設計を踏襲しつつ整理・改善する"
    - question: "データベース戦略"
      decision: "PostgreSQLへ移行（SQLiteから）"
    - question: "MassTransit連携のアーキテクチャ"
      decision: "Elsa標準のMassTransit拡張を使用（独自改造なし、RPC不要）"
    - question: "E2Eテストの構成"
      decision: "C# Playwright (xUnit + Microsoft.Playwright.NUnit) で dotnet test 統一"
  refined_requirements:
    - "MassTransit は Elsa 標準拡張を使用し、独自 ServiceBus 拡張は不要"
    - "RPC Service プロジェクト（src/RpcService）はスコープ外"
    - "Subscribe プロジェクト（src/Subscribe）はスコープ外"
    - "テストは全て dotnet test で統一実行可能にする"
  test_strategy:
    scope:
      - unit
      - integration
      - e2e
    unit:
      framework: "xUnit"
      target: "DLL Loader, WorkflowCatalog, Consumer, PayloadMapper, StatusPublisher, WorkflowLauncher"
      run_command: "dotnet test --filter 'Category!=Integration&Category!=E2E'"
    integration:
      framework: "xUnit"
      target: "Elsa結合（ワークフロー登録・実行・完了）、MassTransit Consumer経由実行"
      run_command: "dotnet test --filter 'Category=Integration'"
      environment: "Docker Compose (PostgreSQL + RabbitMQ)"
    e2e:
      framework: "xUnit + Microsoft.Playwright.NUnit"
      method: "Docker Compose でローカル環境を起動してテスト"
      criteria:
        - "Elsa Studio でアクティビティ一覧にカスタムアクティビティが表示される"
        - "ワークフロー JSON の編集・保存ができる"
        - "ワークフローの実行・停止が GUI から確認できる"
      run_command: "dotnet test --filter 'Category=E2E'"
      environment: "Docker Compose (PostgreSQL + RabbitMQ + ElsaServer)"
  artifacts: "docs/elsa/brainstorming/"
investigation:
  status: completed
  completed_at: "2026-02-20T05:42:59+00:00"
  summary: tmpブランチの全コンポーネントを詳細調査。Activities.Loader, WorkflowCatalog, MassTransit Consumer, テストプロジェクト構成を分析
  artifacts: docs/elsa/investigation/
design:
  status: completed
  completed_at: "2026-02-20T05:42:59+00:00"
  summary: tmpベースの設計をElsa標準MassTransit使用に簡素化。PostgreSQL移行、テスト3層構成
  artifacts: docs/elsa/design/
plan:
  status: completed
  completed_at: "2026-02-20T05:42:59+00:00"
  summary: 4フェーズ実装計画（コアライブラリ→ElsaServer拡張→テスト→ソリューション更新）
  artifacts: docs/elsa/plan/
implement:
  status: completed
  completed_at: "2026-02-20T05:42:59+00:00"
  summary: 全コンポーネント実装完了。ビルド成功、13テスト全通過
  artifacts: submodules/elsa/
