# =============================================================================
# project.yaml — プロジェクトコンテキストファイル（全プロセスの SSOT）
# =============================================================================
# brainstorming プロセスが setup.yaml を基に初期生成。
# 以降の各プロセスが自セクションを追記し、コミットする。

# -----------------------------------------------------------------------------
# メタ情報
# -----------------------------------------------------------------------------
meta:
  version: "1.0"
  ticket_id: "WEB-DESIGN-001"
  task_name: "ウェブデザイン要件定義プロジェクト環境構築"
  target_repo: "web-design"
  branch: "feature/WEB-DESIGN-001"
  created_at: "2026-02-27T11:22:53+00:00"
  updated_at: "2026-02-28T09:36:20+09:00"
# -----------------------------------------------------------------------------
# setup（setup.yaml から引き継ぎ — 読み取り専用）
# -----------------------------------------------------------------------------
setup:
  description:
    overview: |
      dev-processを参考に、ウェブデザインの要件定義を行うためのプロジェクト環境を構築する。
      画面デザインや画面の振る舞いを定義・プレビューできる開発環境を確立し、
      Reactベースの画面モックを作成してcode-server上でプレビューするワークフローを整備する。
    purpose: |
      ウェブアプリケーションの要件定義フェーズにおいて、画面デザインと画面の振る舞いを
      コードベースで定義・検証できる環境を提供する。バックエンドはモックで代替し、
      フロントエンドの画面のみに集中して要件を可視化・共有する。
    background: |
      dev-processリポジトリが提供するdevcontainer構成（DooD/DinD切り替え、開発ツール統合）
      を参考にしつつ、ウェブデザインに特化した環境を構築する。
      tmux起動の代わりにcode-serverを起動し、ブラウザベースのVS Code環境で
      React開発とプレビューを行う。
    requirements:
      functional:
        - "devcontainerのfeatureとしてcode-serverを追加し、コンテナ起動時にcode-serverを自動起動する（tmuxの代替）"
        - "copilot CLI、git、playwright、prettierをdevcontainerに含める"
        - "dev-processと同様のDooD/DinD起動切り替え機構を実装する"
        - "Reactプロジェクトを初期化し、画面コンポーネントを作成できる環境を整える"
        - "code-server上でReactアプリをプレビュー（ホットリロード対応）する方法を確立する"
        - "画面のみを作成し、バックエンドはモックで代替する構成にする"
        - "code-serverにReact開発に必要なVS Code拡張機能をプリインストールする"
        - "code-serverにGitHub Copilot拡張機能をプリインストールする"
      non_functional:
        - "code-serverがブラウザからアクセス可能であること"
        - "Reactアプリのホットリロードがcode-server環境で動作すること"
        - "Playwrightによる画面スクリーンショット・テストが実行可能であること"
    acceptance_criteria:
      - "devcontainerでcode-serverが起動し、ブラウザからアクセスできる"
      - "Reactプロジェクトが初期化され、code-server上でプレビューできる"
      - "DooD/DinD切り替え機構が動作する"
      - "copilot CLI, git, playwright, prettierが使用可能"
      - "code-serverにReact開発用拡張機能がインストールされている"
      - "code-serverにGitHub Copilot拡張機能がインストールされている"
      - "画面デザインのモック作成・プレビューのワークフローが確立されている"
    scope:
      - "devcontainer環境構築（code-server起動、DooD/DinD切り替え）"
      - "Reactプロジェクト初期設定"
      - "code-server用VS Code拡張機能の設定（React開発用 + Copilot）"
      - "画面デザイン・モックのプレビュー環境確立"
      - "Playwrightによるスクリーンショット/テスト環境"
    out_of_scope:
      - "バックエンドAPI実装（モックで代替）"
      - "データベース設計・構築"
      - "本番デプロイ環境"
      - "CI/CDパイプライン"
    notes: |
      dev-processリポジトリの以下の構成を参考にする:
      - .devcontainer/ の構成（devcontainer.json, Dockerfile, docker-compose）
      - scripts/dev-container.sh のDooD/DinD切り替え機構
      - tmuxの代わりにcode-serverを起動する構成に変更
      Reactのビルドツールは Vite を推奨。
      将来的にはdev-processと同様のCopilot向けスキル（.claude/skills/）設定を
      web-designリポジトリにも組み込んでいく予定。初回スコープでは環境構築に集中する。
  related_repositories:
    - name: "dev-process"
      url: "https://github.com/NagasakaH/dev-process.git"
  target_repositories:
    - name: "web-design"
      url: "git@github.com:NagasakaH/web-design.git"
      base_branch: "main"
  options:
    create_design_document: true
    design_document_dir: "docs"
    submodules_dir: "submodules"
# -----------------------------------------------------------------------------
# brainstorming（対話完了後に記入）
# -----------------------------------------------------------------------------
brainstorming:
  status: "completed"
  started_at: "2026-02-27T11:22:53+00:00"
  completed_at: "2026-02-27T11:22:53+00:00"
  summary: |
    React+Vite+TypeScript+Tailwind CSSによるウェブデザイン環境構築を決定。
    devcontainerでcode-serverを起動しブラウザベースで開発、MSWでAPIモック、
    Playwrightでdevcontainer起動後のE2Eテストを実施する方針を確定。
  decisions:
    - question: "フレームワークとビルドツールの選定"
      decision: "React + Vite + TypeScript + Tailwind CSSを採用。Prettierでフォーマット統一"
    - question: "APIモックの方式"
      decision: "MSW (Mock Service Worker) でブラウザ上でAPIレスポンスをモック"
    - question: "devcontainerの構成とベースイメージ"
      decision: "Node.js LTS (mcr.microsoft.com/devcontainers/javascript-node:lts) をベースに、DockerHub (nagasakah/web-design:base) にプリビルドイメージをプッシュ"
    - question: "開発サーバーの起動方法"
      decision: "code-server (tmux起動の代替) でブラウザベースのVS Code環境を提供。npm run devでVite開発サーバーを起動しポートフォワードでプレビュー"
    - question: "テスト戦略"
      decision: "E2Eテストのみ。Playwrightでdevcontainerビルド→起動後にcode-serverアクセス、Reactプレビュー、拡張機能、DooD/DinD切り替えを検証"
  refined_requirements:
    - "VS Code拡張機能: GitHub Copilot, Copilot Chat, ES7+ React snippets, ESLint, Prettier, Tailwind CSS IntelliSense, YAML"
    - "DooD/DinD切り替えはdev-processと同様のDOCKER_MODE環境変数による切り替え機構を実装"
    - "将来的にdev-processと同様のCopilot向けスキル（.claude/skills/）をweb-designにも組み込む予定（初回スコープ外）"
  test_strategy:
    scope:
      - "e2e"
    e2e:
      method: "devcontainerをビルド→起動し、Playwrightで動作確認"
      criteria:
        - "code-serverがブラウザからアクセス可能か"
        - "Reactアプリがプレビューできるか"
        - "VS Code拡張機能がインストールされているか"
        - "DooD/DinD切り替えが動作するか"
      environment: "devcontainer (ローカル Docker)"
  artifacts: "docs/web-design/brainstorming/"
investigation:
  status: completed
  started_at: "2026-02-27T11:33:55+00:00"
  summary: "dev-processのdevcontainer構成（2段階ビルド、DooD/DinD切替、tmux起動）を詳細調査し、web-designへのcode-server起動環境移植方針を確立。GitHub Copilot拡張のOpen VSX制約が最大リスク。"
  key_findings:
    - dev-processは2段階ビルド（devcontainer build→Dockerfile）パターンを採用。web-designも同様に構成する
    - start-tmux.shのUID/GID調整・Docker socket パーミッション修正ロジックはcode-server版でもそのまま必要
    - DooD時はENTRYPOINTを上書きしてdocker-init.shをスキップするパターンが重要（--entrypoint start-code-server）
    - code-serverのdevcontainer featureは公式に存在しない。Dockerfile内でcurl install.shによるインストールが必要
    - GitHub Copilot拡張機能はOpen VSX Registryに公開されておらず、VSIX手動インストールまたはmarketplace.json上書きが必要
  risks:
    - code-serverでGitHub Copilot拡張機能が動作しない可能性（Open VSX制約）→ VSIX手動インストールまたはCopilot CLI代替
    - Vite HMRがbind mount環境で不安定になる可能性 → usePolling設定で対応
    - dev-container.shにポートマッピング（-p 8080:8080 -p 5173:5173）の追加が必要
  artifacts: "docs/web-design/investigation/"
  completed_at: "2026-02-27T11:34:18+00:00"
design:
  status: approved
  started_at: "2026-02-27T11:42:09+00:00"
  summary: "dev-processの2段階ビルドパターンを踏襲し、Node.js LTS + code-server構成に置換。tmux→code-server起動、DooD/DinD切替移植、React+Vite+TypeScript+Tailwind CSS+MSW環境を設計"
  approach: "devcontainer.json(9 features) + Dockerfile(code-server+拡張機能インストール) + start-code-server.sh(UID/GID調整+code-server起動) + dev-container.sh(DooD/DinD切替移植) + Vite+React+TypeScript+Tailwind CSS"
  key_decisions:
    - code-serverをDockerfile内でcurl installによりインストール（devcontainer feature非対応のため）
    - GitHub Copilot拡張はOpen VSXに非公開のためCopilot CLIで代替（devcontainer feature copilot-cli:1で導入済み）
    - Vite HMRはusePolling設定でbind mount環境に対応
    - DooD時は--entrypoint start-code-serverでdocker-init.shをスキップ
    - E2Eテストのみ（Playwrightでdevcontainer起動後の動作確認）
  review:
    round: 2
    status: approved
    latest_verdict: 承認
    completed_at: "2026-02-27T12:01:54+00:00"
    summary: Round 2完了。Minor 3件（MRD-R2-001, MRD-R2-002, MRD-012）を修正し全指摘解決。承認。
    issues:
      - id: MRD-001
        severity: major
        category: 要件整合性
        description: setup.yamlの要件「devcontainerのfeatureとしてcode-serverを追加」に対し、設計はDockerfileでの手動インストール前提。実現手段を明記する必要あり
        status: resolved
      - id: MRD-002
        severity: major
        category: Open VSX制約対応
        description: Copilot拡張のDockerfileインストールが || true で失敗許容。Open VSXにCopilotは非公開で100%失敗する。Copilot CLIフォールバックの設計方針を明確化する必要あり
        status: resolved
      - id: MRD-003
        severity: major
        category: 実装可能性
        description: E2Eテストコード内の docker exec <container> がプレースホルダー。コンテナ名動的取得のヘルパー設計が必要
        status: resolved
      - id: MRD-004
        severity: major
        category: テスト可能性
        description: 'acceptance_criteriaの未検証項目: Copilot拡張→CLIフォールバック確認、copilot CLIバージョン確認、HMR反映確認、MSWモック応答確認'
        status: resolved
      - id: MRD-005
        severity: minor
        category: セキュリティ
        description: code-server --auth none等のリスクガード不足。ローカル限定・公開ネットワーク禁止を明文化
        status: resolved
      - id: MRD-006
        severity: minor
        category: テスト設計
        description: DooD/DinDモード切替テストの実行方法が未設計
        status: resolved
      - id: MRD-007
        severity: minor
        category: ファイル構造
        description: investigation文書との tailwind.config.js 不整合。Tailwind CSS v4ではCSS-first設定で不要であることを明記
        status: resolved
      - id: MRD-008
        severity: minor
        category: MSW初期化
        description: main.tsxでのMSW初期化パターンが未設計
        status: resolved
      - id: MRD-009
        severity: minor
        category: ESLint設定
        description: eslint.config.jsの具体的設定が未設計
        status: resolved
      - id: MRD-010
        severity: info
        category: スコープ
        description: claude-code featureがスコープ外だが追加されている
        status: resolved
      - id: MRD-011
        severity: info
        category: 重複
        description: Prettierがfeatureとnpm両方に存在
        status: resolved
    artifacts:
      - docs/web-design/review-design/06_review-summary.md
      - docs/web-design/review-design/round-02.md
  artifacts: "docs/web-design/design/"
  completed_at: "2026-02-27T12:01:33+00:00"
plan:
  status: reviewed
  started_at: "2026-02-27T12:09:38+00:00"
  summary: "review-plan round 1完了: Major 5件 + Minor 5件を修正"
  total_tasks: 6
  tasks:
    - id: task01
      title: devcontainer構成ファイル作成
      status: pending
    - id: task02-01
      title: dev-container.sh作成
      status: pending
    - id: task02-02
      title: build-and-push-devcontainer.sh作成
      status: pending
    - id: task02-03
      title: Reactプロジェクト初期化・ソースコード・MSW設定
      status: pending
    - id: task03
      title: Playwright E2Eテスト作成
      status: pending
    - id: task04
      title: README.md作成
      status: pending
  review:
    round: 2
    status: approved
    summary: Major 5件 + Minor 5件を修正済。TDDフロー整備、受入基準修正、MSW SW生成追加、playwright.config.ts配置統一、verification検証チェックリスト追加
    artifacts:
      - docs/web-design/review-plan/round-01.md
  artifacts: "docs/web-design/review-plan/round-01.md"
  completed_at: "2026-02-27T12:10:02+00:00"
implement:
  status: completed
  started_at: "2026-02-27T12:34:34+00:00"
  completed_tasks: 6
  total_tasks: 6
  tasks:
    - id: task01
      title: devcontainer構成ファイル作成
      status: completed
      commit: 52a50f5
    - id: task02-01
      title: dev-container.sh作成
      status: completed
      commit: fdc238c
    - id: task02-02
      title: build-and-push-devcontainer.sh作成
      status: completed
      commit: 849628f
    - id: task02-03
      title: Reactプロジェクト初期化・ソースコード・MSW設定
      status: completed
      commit: 04c508f
    - id: task03
      title: Playwright E2Eテスト作成
      status: completed
      commit: 883819b
    - id: task04
      title: README.md作成
      status: completed
      commit: 89dea9e
  artifacts: "docs/web-design/implement/"
  completed_at: "2026-02-27T12:44:06+00:00"
verification:
  status: completed
  started_at: "2026-02-27T12:49:31+00:00"
  results:
    test:
      status: skip
      detail: ""
    build:
      status: pass
      detail: "tsc -b && vite build 成功。30モジュール変換"
    lint:
      status: pass
      detail: "ESLint エラーなし"
    typecheck:
      status: pass
      detail: "tsc --noEmit エラーなし（E2Eファイル含む）"
    format:
      status: pass
      detail: Prettier 9ファイル修正後、全ファイルパス
    e2e:
      status: not_executed
      detail: devcontainer環境が必要。テストファイル構文チェック・一覧確認はパス（10テスト）
  acceptance_criteria_check:
    - criteria: devcontainerでcode-serverが起動しブラウザからアクセスできる
      verified_by: e2e_test
      result: not_verified
      note: devcontainer起動後に検証
    - criteria: Reactプロジェクトが初期化されプレビューできる
      verified_by: build + e2e_test
      result: partial
      note: ビルド成功確認済、プレビューはdevcontainer起動後
    - criteria: DooD/DinD切り替え機構が動作する
      verified_by: e2e_test
      result: not_verified
      note: devcontainer起動後に検証
    - criteria: copilot CLI, git, playwright, prettierが使用可能
      verified_by: local + e2e_test
      result: partial
      note: prettier,playwright確認済。copilot CLI/gitはdevcontainer起動後
    - criteria: code-serverにGitHub Copilot拡張機能がインストールされている
      verified_by: e2e_test
      result: not_verified
      note: devcontainer起動後に検証
    - criteria: code-serverにReact開発用拡張機能がインストールされている
      verified_by: e2e_test
      result: not_verified
      note: devcontainer起動後に検証
    - criteria: 画面デザインのモック作成・プレビューのワークフローが確立されている
      verified_by: build + e2e_test
      result: partial
      note: ビルド成功・MSW設定確認済。HMR/プレビューはdevcontainer起動後
  summary: "E2Eテスト全10件実施: 9 passed, 1 skipped (E2E-6 DooDテストはDinDモードのため正しくスキップ)"
  evidence: []
  artifacts:
    - docs/web-design/verification/results.md
  completed_at: "2026-02-28T05:24:13+09:00"
code_review:
  status: approved
  started_at: "2026-02-27T12:59:40+00:00"
  round: 3
  rounds: []
  review_checklist: {}
  issues:
    - id: MCR-001
      severity: major
      category: security
      description: docker.sock chmod 666 → chmod 660 + dockerグループ追加
      status: fixed
      fixed_description: chmod 660に変更、dockerグループ作成・vscodeユーザー追加
    - id: MCR-002
      severity: major
      category: security
      description: execInContainer コマンドインジェクション
      status: fixed
      fixed_description: execFileSync使用 + containerNameバリデーション追加
    - id: MCR-003
      severity: major
      category: test-quality
      description: DinD/DooDテスト同一
      status: fixed
      fixed_description: 各モード固有検証 + DOCKER_MODEスキップ制御追加
    - id: MCR-004
      severity: major
      category: git-practice
      description: tsbuildinfo コミット
      status: fixed
      fixed_description: .gitignore追加 + git rm --cached
    - id: MCR-005
      severity: minor
      category: error-handling
      description: MSW init エラーハンドリング欠落
      status: fixed
      fixed_description: .catch()追加しフォールバック描画
    - id: MCR-006
      severity: minor
      category: config
      description: .editorconfig 欠落
      status: fixed
      fixed_description: .editorconfig新規作成
    - id: MCR-007
      severity: minor
      category: config
      description: .prettierignore 欠落
      status: fixed
      fixed_description: .prettierignore新規作成
    - id: MCR-008
      severity: minor
      category: test-quality
      description: msw.spec.ts waitForTimeout
      status: fixed
      fixed_description: waitForFunction(SW controller check)に変更
    - id: MCR-009
      severity: minor
      category: code-quality
      description: root element non-null assertion
      status: fixed
      fixed_description: 明示的nullチェック + エラーメッセージ
  artifacts:
    - docs/web-design/code-review/round-01.md
    - docs/web-design/code-review/round-02.md
    - docs/web-design/code-review/round-03.md
  summary: 'Round 3: E2Eテスト実施時バグ修正のレビュー。Critical/Major/Minor指摘なし。全チェック通過。'
  completed_at: "2026-02-28T09:36:20+09:00"
  base_sha: ac75285
  head_sha: 296ad6b
  latest_verdict: 承認
finishing:
  status: completed
  started_at: "2026-02-27T13:11:24+00:00"
  action: keep
  method: pull_request
  pr_url: https://github.com/NagasakaH/web-design/pull/1
  completed_at: "2026-02-27T13:11:24+00:00"
